name: cast_ui_example
description: Demonstrates how to use the cast_ui plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cast_ui:
    path: ../
  flutter:
    sdk: flutter
  http: ^0.13.3
  video_player: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  bonsoir:
    git:
      url: git@github.com:Skyost/Bonsoir.git
      path: bonsoir
      ref: master
  cast:
    git:
      url: git@github.com:vanlooverenkoen/flutter_cast.git
      ref: bugfix/bonsoir-master

flutter:
  uses-material-design: true
