name: cast_ui_example
description: Demonstrates how to use the cast_ui plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cast_ui:
    path: ../
  flutter:
    sdk: flutter
  http: ^0.13.3
  video_player: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
