name: cast_ui
description: A plugin that simplifies the cast plugin by providing a basic U
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  cast: ^1.1.0
  flutter:
    sdk: flutter
  provider: ^5.0.0
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  cast:
    git:
      url: git@github.com:vanlooverenkoen/flutter_cast.git
      ref: bugfix/bonsoir-master

flutter:
  plugin:
    platforms:
      android:
        package: be.vanlooverenkoen.cast.ui.cast_ui
        pluginClass: CastUiPlugin
      ios:
        pluginClass: CastUiPlugin